config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :users, only: [ :show, :edit, :update ]
  resources :camps do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookings, only: [:index, :destroy, :show, :edit, :update] do

  end
  resources :reviews, only: [:edit, :update, :destroy]

  get "camp/:id", to: "pages#camp", as: :my_camp
  get "my_camps", to: "pages#my_camps", as: :my_camps
  put "camp/:id", to: "pages#confirm_booking"
  get "filter", to: "pages#filter", as: :camps_filter
end

app/models/booking.rb
class Booking < ApplicationRecord
  # associations
  belongs_to :user
  belongs_to :camp
  # validations
  validates :surfers, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_camps, only: [:new, :create]
  before_action :set_booking, only: [:edit, :update, :show, :destroy]

  layout "application"

  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.camp = @camp
    @booking.user = current_user
    if @booking.save
        redirect_to camp_path(@camp)
      else
        render 'camps/show'
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    if @booking.save
      redirect_to bookings_path
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :surfers, :camp_id)
  end

  def set_camps
    @camp = Camp.find(params[:camp_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
  def elper(booking)
    if booking.accepted
      "accepted"
    else
      "pending"
    end
  end
end

app/views/bookings/_index.html.erb
<% @bookings.each do |booking| %>
     <% if booking.camp.photo? %>
      <div class="card-prof" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path booking.camp.photo %>');">
    <% else %>
      <div class="card-prof" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path 'background.png' %>'); background-position: 1% 25%;">

    <% end %>
         <div class="card-title"><%= booking.camp.title %></div>
         <div class="card-date">
         From :
           <%= booking.start_date.strftime('%d/%m/%Y') %>
          to :
           <%= booking.end_date.strftime('%d/%m/%Y') %>
         </div>
         <div class="card-accepted">Reservation <%= elper(booking) %> for <%= booking.camp.price %> $</div>

          <!-- Trigger the modal with a button -->
          <button type="button" class="btn btn-primary card-prof-btn" data-toggle="modal" data-target="#booking-modal-<%= booking.id %>">Add a review</button>

          <%= link_to "", booking_path(booking), class: "link-card-prof" %>
    </div>
  <!-- Modal -->
  <div id="booking-modal-<%= booking.id %>" class="modal fade" role="dialog">
    <div class="modal-dialog">
     <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add a review</h4>
        </div>
        <div class="modal-body">
            <%= render 'reviews/form', camp: booking.camp %>
        </div>

      </div>

    </div>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<%= simple_form_for( @booking ) do |f| %>
  <%= f.input :start_date, as: :string, input_html: { class: "datepicker" }, placeholder: 'Change starting date' %>
  <%= f.input :end_date, as: :string, input_html: { class: "datepicker" }, placeholder: 'Change ending date' %>
  <%= f.input :surfers, collection: 1..12, selected: 1, label: "For how many surfers?" %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<%= link_to 'Cancel Booking', booking_path(@booking), method: :delete,  data: { confirm: "Are you sure you want to cancel this booking?" }, class: "btn btn-danger" %>
<br>
<%= link_to 'Back to my bookings', bookings_path%>

app/views/bookings/show.html.erb
<% photo = @booking.camp.photo %>
<div class="banner-detail" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= photo %>');">
  <div class="banner-content">
    <h1><%= @booking.camp.title %></h1>
  </div>
</div>


<div class="btn btn-info"><i class="fa fa-chevron-left" aria-hidden="true"></i><%= link_to ' Back to My Bookings', user_path(current_user) %></div>


<div class="container detail-intro">
  <div class="row">
    <div class= "col-sm-9 col-xs-12 camp-summary">
      <h1><%= @booking.camp.title %></h1>
      <div class="description-look"> <%= @booking.camp.address %></div>
   </div>

   <div class= "col-sm-3 col-xs-12 price-box-container">
    <div class="price-look text-center"><%= @booking.camp.price %>$</div>
  </div>
</div>
</div>
<!-- Booking info-->
<div class="container description-camp">
  <div class="row">
    <div class="col-xs-12">
      <h3>Info booking:</h3>
          <div class="col-md-6 book-recap">
      <p> Start date :
          <%= @booking.start_date.strftime('%d/%m/%Y')  %></p>
      <p> End date:
          <%= @booking.end_date.strftime('%d/%m/%Y') %> </p>
      <p> Number of surfers:   <%= @booking.surfers %> </p>
    </div>

    </div>
  </div>
</div>
<!-- Description -->
<div class="container description-camp">
  <div class="row">
    <div class="col-xs-12">
      <h3>Description:</h3>
      <p><%= @booking.camp.description %></p>
    </div>
  </div>
</div>
<!-- Reviews -->
<div class="container reviews-camp">
  <div class="row">
    <div class="col-md-12">
      <h3>Reviews:</h3>
      <% @booking.camp.reviews.each do |review| %>
      <div class="review">
        <div class='avatar-review'>
        <%= image_tag(review.user.photo, class: "avatar-review") %>
        </div>
        <div class='review-body'>
          <h3><%= review.title %></h3>
          <p><%= review.description %></p>
        </div>
        <ul class="list-inline product-controls hidden-sm hidden-xs">
          <% review.rating.times do %>
              <i class="fa fa-star" style="color: #ffb400"></i>
            <% end %>
            <% (5 - review.rating).times do %>
             <i class="fa fa-star" style="color: gray"></i>
            <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
</div>