config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :users, only: [ :show, :edit, :update ]
  resources :camps do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookings, only: [:index, :destroy, :show, :edit, :update] do

  end
  resources :reviews, only: [:edit, :update, :destroy]

  get "camp/:id", to: "pages#camp", as: :my_camp
  get "my_camps", to: "pages#my_camps", as: :my_camps
  put "camp/:id", to: "pages#confirm_booking"
  get "filter", to: "pages#filter", as: :camps_filter
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
<div id="wave" style="background-image: linear-gradient(-270deg, #6EB6FF 0%, #90F2FF 100%); margin-top:-1px";>
   <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1170 193" style="fill: white; margin-top: -2px">
     <path d="M1175 131.2c0 0-81-89.4-224.3-103.4S713 72 665 97c-86 46-148 63-271 7C221.7 25.5 56 104.5-4 197.4 -4 58.7-3.3 0.3-3.3 0.3L1175 0V131.2z"/>
   </svg>
</div>
<div class="wrapper" style="background-image: linear-gradient(-270deg, #6EB6FF 0%, #90F2FF 100%); height: 7vh">
</div>
<div class="footer-content text-center">
  <ul class="list-inline">
    <li><i class="fa fa-facebook"></i></li>
    <li><i class="fa fa-twitter"></i></li>
    <li><i class="fa fa-instagram"></i></li>
  </ul>
  <p>Made with ️🤘🏽 @ LeWagon</p>
</div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo6.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= link_to destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" do %>
            <%= t(".sign_out", default: "Log out") %>
          <% end %>
          <% if !current_user.facebook_picture_url.nil? %>
            <% avatar_url = current_user.facebook_picture_url %>
          <%elsif !current_user.photo.nil? %>
            <% avatar_url = current_user.photo %>
          <% else %>
            <% avatar_url = "http://placehold.it/30x30" %>
          <% end %>
          <%= link_to image_tag(avatar_url, class: "avatar"), user_path(current_user)%>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Create a Camp"), new_camp_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>