config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :users, only: [ :show, :edit, :update ]
  resources :camps do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookings, only: [:index, :destroy, :show, :edit, :update] do

  end
  resources :reviews, only: [:edit, :update, :destroy]

  get "camp/:id", to: "pages#camp", as: :my_camp
  get "my_camps", to: "pages#my_camps", as: :my_camps
  put "camp/:id", to: "pages#confirm_booking"
  get "filter", to: "pages#filter", as: :camps_filter
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :set_camp, only: [:index, :new]
before_action :set_review, only: [ :edit, :update ]


  def index
    @reviews = @camp.reviews
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.camp = Camp.find(params[:camp_id])
    @camp = @review.camp
    if @review.save
        redirect_to camp_path(@camp)
      else
        render 'camps/show'
    end
  end

  def edit
  end

  def update
    @review.update(review_params)
    if @review.save
      redirect_to user_path(@review.user)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to :back
  end


  private

  def review_params
    params.require(:review).permit(:title, :description, :rating)
  end

  def set_camp
    @camp = Camp.find(params[:camp_id])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_review
     @review = Review.find(params[:id])
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for [camp, Review.new] do |f| %>
    <%= f.input :title, placeholder: "Summarize your experience in a short title", label: false, :class => "form-field", required: true %>
    <%= f.input :description, placeholder: "Tell us why your experience was great (e.i. : John was a great teacher, I can't wait to come back with my whole family next year)", label: false, :class => "form-field" %>
    <%= f.input :rating, placeholder: "Give a rating between 1(min) and 5(max) to your experience", label:false, :class => "form-field", required: true %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/reviews/_my_reviews.html.erb
<% @user.reviews.each do |review| %>
  <div class="box-review">
    <div class="review-title"> <%= review.title %></div>
    <ul class="list-inline product-controls hidden-sm hidden-xs review-dashboard-rating">
      <% review.rating.times do %>
          <i class="fa fa-star" style="color: #ffb400"></i>
        <% end %>
        <% (5 - review.rating).times do %>
         <i class="fa fa-star" style="color: gray"></i>
        <% end %>
    </ul>
    <div class="review-description"> <%= review.description %></div>

    <div class= "edit-reviews-pencil">
      <%= link_to edit_review_path(review) do %>
        <i class="fa fa-pencil" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class= "delete-reviews-pencil">
      <%= link_to review_path(review), method: :delete, data: {confirm: "Are you sure you want to delete this review?"} do %>
        <i class="fa fa-trash" aria-hidden="true"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h3>Edit your review</h3>

<%= simple_form_for @review do |f| %>
    <%= f.input :title, placeholder: "Summurize your experience in a short title", label: false, :class => "form-field", required: true %>
    <%= f.input :description, placeholder: "Tell us why your experience was great (e.i. : John was a great teacher, I can't wait to come back with my whole family next year)", label: false, :class => "form-field" %>
    <%= f.input :rating, placeholder: "Give a rating between 1(min) and 5(max) to your experience", label:false, :class => "form-field", required: true %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/reviews/new.html.erb
<h3>Leave a review to <%= @camp.title %></h3>

<%= simple_form_for [@camp, @review] do |f| %>
    <%= f.input :title, placeholder: "Summurize your experience in a short title", label: false, :class => "form-field", required: true %>
    <%= f.input :description, placeholder: "Tell us why your experience was great (e.i. : John was a great teacher, I can't wait to come back with my whole family next year)", label: false, :class => "form-field" %>
    <%= f.input :rating, placeholder: "Give a rating between 1(min) and 5(max) to your experience", label:false, :class => "form-field", required: true %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>